-- The tables that make the control plane an OAuth authorization server for model-context
-- clients (ADR 0061, the second half of ADR 0060).
--
-- A claude.ai connector cannot be handed a personal token: it speaks MCP to a URL, follows the
-- 401's `resource_metadata` to this server, registers itself, sends the person here to sign in,
-- and comes back with an access token. Better Auth's `@better-auth/mcp` plugin (over its
-- `@better-auth/oauth-provider`) is that server, and `jwt()` signs the tokens it issues. Every
-- table below is WRITTEN BY THAT LIBRARY, not by our SQL, which is why they follow
-- `060_auth.sql` rather than the rest of this directory:
--
--   - Names are ours, mapped back to the library's models in `handlers/auth.ts`
--     (`authOptions`): `oauth_*` for the provider's, `auth_jwks` beside the other `auth_*`.
--   - Columns are TRANSCRIBED from the plugins' exported `schema` (1.7.5), snake_cased, and
--     typed the way Better Auth's own Postgres migrator types them: `string` -> text, `date` ->
--     timestamptz, `boolean` -> boolean, `number` -> integer, and both `string[]` and `json`
--     -> jsonb (its Kysely adapter writes an array as JSON text). `authSchema.test.ts` walks
--     the library's schema field by field against this file, so an upgrade that adds a field
--     fails the gate rather than the first consent in production.
--   - `text` ids, generated by the library, for the reason 060 gives.
--   - NOT NULL only where the library marks a field required, which is where it always writes
--     one; everything else is nullable, because a NOT NULL on a column a third party fills is a
--     runtime landmine (060). Foreign keys follow the schema's `references`, with the library's
--     own default of `ON DELETE CASCADE` except where it says `set null`.
--
-- What is NOT stored: an access token. Tokens for `/mcp` are JWTs bound to the `/mcp` resource
-- and verified against `auth_jwks` in process; `oauth_access_token` exists for the opaque kind
-- the provider issues when no resource is named, which `/mcp` refuses. Refresh tokens and client
-- secrets are stored hashed (the provider's `storeTokens` / `storeClientSecret` defaults), and
-- a signing key's private half is encrypted with `UNDERCROFT_SESSION_SECRET` by `jwt()`.

-- -- app.auth_jwks -----------------------------------------------------------
-- The keys access tokens are signed with. Rotating `UNDERCROFT_SESSION_SECRET` makes every
-- private key here unreadable, exactly as it ends every session.
CREATE TABLE IF NOT EXISTS app.auth_jwks (
    id          text PRIMARY KEY,
    public_key  text NOT NULL,
    private_key text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz,
    alg         text,
    crv         text
);

-- -- app.oauth_client ---------------------------------------------------------
-- A registered client: a connector that registered itself (RFC 7591), with no owner --
-- `user_id` is empty for all of them, because registration is open. A client can do nothing
-- until a person signs in and consents; see `oauth_consent`.
CREATE TABLE IF NOT EXISTS app.oauth_client (
    id                                  text PRIMARY KEY,
    client_id                           text NOT NULL UNIQUE,
    client_secret                       text,
    client_discovery_id                 text,
    disabled                            boolean DEFAULT false,
    skip_consent                        boolean,
    enable_end_session                  boolean,
    subject_type                        text,
    scopes                              jsonb,
    client_credentials_scopes           jsonb DEFAULT '[]'::jsonb,
    user_id                             text REFERENCES app.auth_user(id) ON DELETE CASCADE,
    created_at                          timestamptz,
    updated_at                          timestamptz,
    name                                text,
    uri                                 text,
    icon                                text,
    contacts                            jsonb,
    tos                                 text,
    policy                              text,
    software_id                         text,
    software_version                    text,
    software_statement                  text,
    redirect_uris                       jsonb NOT NULL,
    post_logout_redirect_uris           jsonb,
    backchannel_logout_uri              text,
    backchannel_logout_session_required boolean,
    token_endpoint_auth_method          text,
    application_type                    text,
    jwks                                text,
    jwks_uri                            text,
    grant_types                         jsonb,
    response_types                      jsonb,
    require_pkce                        boolean,
    dpop_bound_access_tokens            boolean DEFAULT false,
    reference_id                        text,
    metadata                            jsonb
);

CREATE INDEX IF NOT EXISTS oauth_client_user_id_idx ON app.oauth_client (user_id);

-- -- app.oauth_resource -------------------------------------------------------
-- A protected resource tokens are issued for. There is one: `<public origin>/mcp`, seeded by
-- the plugin at boot from its `resource` option (insert-only, so a row is never rewritten).
CREATE TABLE IF NOT EXISTS app.oauth_resource (
    id                                text PRIMARY KEY,
    identifier                        text NOT NULL UNIQUE,
    name                              text NOT NULL,
    access_token_ttl                  integer,
    refresh_token_ttl                 integer,
    signing_algorithm                 text,
    signing_key_id                    text,
    allowed_scopes                    jsonb,
    custom_claims                     jsonb,
    dpop_bound_access_tokens_required boolean DEFAULT false,
    disabled                          boolean DEFAULT false,
    created_at                        timestamptz,
    updated_at                        timestamptz,
    policy_version                    integer DEFAULT 1,
    metadata                          jsonb
);

-- -- app.oauth_client_resource ------------------------------------------------
-- Which client may ask for which resource. Every registered client is linked to `/mcp` at
-- registration; the pair is unique because the provider's check assumes one row per pair.
CREATE TABLE IF NOT EXISTS app.oauth_client_resource (
    id          text PRIMARY KEY,
    client_id   text NOT NULL REFERENCES app.oauth_client(client_id) ON DELETE CASCADE,
    resource_id text NOT NULL REFERENCES app.oauth_resource(identifier) ON DELETE CASCADE,
    metadata    jsonb,
    created_at  timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS oauth_client_resource_pair_idx
    ON app.oauth_client_resource (client_id, resource_id);
CREATE INDEX IF NOT EXISTS oauth_client_resource_resource_id_idx
    ON app.oauth_client_resource (resource_id);

-- -- app.oauth_refresh_token --------------------------------------------------
-- What lets a connector come back after its access token lapses (ADR 0062). Revoking an
-- app on the account page stamps `revoked` on these, so the connector cannot get a new one.
CREATE TABLE IF NOT EXISTS app.oauth_refresh_token (
    id                         text PRIMARY KEY,
    token                      text NOT NULL UNIQUE,
    client_id                  text NOT NULL REFERENCES app.oauth_client(client_id) ON DELETE CASCADE,
    session_id                 text REFERENCES app.auth_session(id) ON DELETE SET NULL,
    user_id                    text NOT NULL REFERENCES app.auth_user(id) ON DELETE CASCADE,
    reference_id               text,
    authorization_code_id      text,
    resources                  jsonb,
    requested_user_info_claims jsonb,
    expires_at                 timestamptz,
    created_at                 timestamptz,
    revoked                    timestamptz,
    rotated_at                 timestamptz,
    rotation_replay_response   text,
    rotation_replay_expires_at timestamptz,
    auth_time                  timestamptz,
    confirmation               jsonb,
    scopes                     jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS oauth_refresh_token_client_id_idx ON app.oauth_refresh_token (client_id);
CREATE INDEX IF NOT EXISTS oauth_refresh_token_session_id_idx ON app.oauth_refresh_token (session_id);
CREATE INDEX IF NOT EXISTS oauth_refresh_token_user_id_idx ON app.oauth_refresh_token (user_id);
CREATE INDEX IF NOT EXISTS oauth_refresh_token_authorization_code_id_idx
    ON app.oauth_refresh_token (authorization_code_id);

-- -- app.oauth_access_token ---------------------------------------------------
-- OPAQUE access tokens only -- see the header. `/mcp` never reads this table.
CREATE TABLE IF NOT EXISTS app.oauth_access_token (
    id                         text PRIMARY KEY,
    token                      text UNIQUE,
    client_id                  text NOT NULL REFERENCES app.oauth_client(client_id) ON DELETE CASCADE,
    session_id                 text REFERENCES app.auth_session(id) ON DELETE SET NULL,
    user_id                    text REFERENCES app.auth_user(id) ON DELETE CASCADE,
    reference_id               text,
    authorization_code_id      text,
    resources                  jsonb,
    requested_user_info_claims jsonb,
    refresh_id                 text REFERENCES app.oauth_refresh_token(id) ON DELETE CASCADE,
    expires_at                 timestamptz,
    created_at                 timestamptz,
    revoked                    timestamptz,
    confirmation               jsonb,
    scopes                     jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS oauth_access_token_client_id_idx ON app.oauth_access_token (client_id);
CREATE INDEX IF NOT EXISTS oauth_access_token_session_id_idx ON app.oauth_access_token (session_id);
CREATE INDEX IF NOT EXISTS oauth_access_token_user_id_idx ON app.oauth_access_token (user_id);
CREATE INDEX IF NOT EXISTS oauth_access_token_authorization_code_id_idx
    ON app.oauth_access_token (authorization_code_id);
CREATE INDEX IF NOT EXISTS oauth_access_token_refresh_id_idx ON app.oauth_access_token (refresh_id);

-- -- app.oauth_consent --------------------------------------------------------
-- What a person agreed a client may do: the scopes they approved on `/consent`, which is where
-- `undercroft:read` or `undercroft:write` is chosen. `/mcp` reads this row on EVERY request
-- (`handlers/context.ts`), so deleting it -- "Revoke" on the account page -- stops the
-- client at its next call, whatever its access token still says.
CREATE TABLE IF NOT EXISTS app.oauth_consent (
    id                         text PRIMARY KEY,
    client_id                  text NOT NULL REFERENCES app.oauth_client(client_id) ON DELETE CASCADE,
    user_id                    text REFERENCES app.auth_user(id) ON DELETE CASCADE,
    reference_id               text,
    resources                  jsonb,
    requested_user_info_claims jsonb,
    scopes                     jsonb NOT NULL,
    created_at                 timestamptz,
    updated_at                 timestamptz
);

CREATE INDEX IF NOT EXISTS oauth_consent_client_id_idx ON app.oauth_consent (client_id);
CREATE INDEX IF NOT EXISTS oauth_consent_user_id_idx ON app.oauth_consent (user_id);

-- -- app.oauth_client_assertion -----------------------------------------------
-- Single-use `jti`s of `private_key_jwt` client assertions; the id IS the digest, so a replay
-- collides on the primary key. Nothing prunes it yet -- the library says so too.
CREATE TABLE IF NOT EXISTS app.oauth_client_assertion (
    id         text PRIMARY KEY,
    expires_at timestamptz NOT NULL
);

-- -- grants -------------------------------------------------------------------------------
-- In this file, for the reason `privileges.md` and 060 give: 040's `ON ALL TABLES IN SCHEMA
-- app` was expanded against the tables that existed when it ran, so a table added later has NO
-- grants, and the symptom is "permission denied for table" at the first consent with the suite
-- green.
GRANT SELECT, INSERT, UPDATE, DELETE ON
    app.auth_jwks, app.oauth_client, app.oauth_resource, app.oauth_client_resource,
    app.oauth_refresh_token, app.oauth_access_token, app.oauth_consent,
    app.oauth_client_assertion
    TO undercroft_app;

-- Nothing for `undercroft_worker`: it never signs a person in and never admits a person's
-- credential. Nothing for any dbt or BI role: they have no USAGE on `app` at all (040). Stated
-- rather than omitted, so adding a grant here means contradicting a sentence.

-- No ALTER DEFAULT PRIVILEGES: none is written by hand anywhere (080_tenant_isolation.sql).
